"""create frozen Lite schema

Revision ID: 0001_lite_schema
Revises:
Create Date: frozen

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_lite_schema'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_revision',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('manifest_json', sa.Text(), nullable=False),
    sa.Column('parameter_schema_json', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("kind IN ('BUILT_IN', 'SERVICE')", name='agent_kind'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    with op.batch_alter_table('agent_revision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_revision_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_revision_name'), ['name'], unique=False)

    op.create_table('app_setting',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_setting_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_setting_key'), ['key'], unique=True)

    op.create_table('artifact',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('ref_type', sa.String(length=64), nullable=False),
    sa.Column('ref_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_ref_id'), ['ref_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_ref_type'), ['ref_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_sha256'), ['sha256'], unique=False)

    op.create_table('benchmark_revision',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('adapter_name', sa.String(length=128), nullable=False),
    sa.Column('manifest_json', sa.Text(), nullable=False),
    sa.Column('tool_schema_json', sa.Text(), nullable=False),
    sa.Column('evaluation_protocol_json', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    with op.batch_alter_table('benchmark_revision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_benchmark_revision_adapter_name'), ['adapter_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_benchmark_revision_created_at'), ['created_at'], unique=False)

    op.create_table('local_user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'DISABLED')", name='local_user_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('local_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_local_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_local_user_username'), ['username'], unique=True)

    op.create_table('secret_ref',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('ciphertext', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('UNVERIFIED', 'VALID', 'INVALID')", name='secret_ref_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('secret_ref', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_secret_ref_created_at'), ['created_at'], unique=False)

    op.create_table('audit_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['local_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_event_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_entity_type'), ['entity_type'], unique=False)

    op.create_table('dataset_version',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('benchmark_revision_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('manifest_json', sa.Text(), nullable=False),
    sa.Column('split', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=9), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'PUBLISHED', 'RETIRED')", name='dataset_status'),
    sa.ForeignKeyConstraint(['benchmark_revision_id'], ['benchmark_revision.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    with op.batch_alter_table('dataset_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_version_benchmark_revision_id'), ['benchmark_revision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_version_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_version_name'), ['name'], unique=False)

    op.create_table('model_config_revision',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=256), nullable=False),
    sa.Column('secret_ref_id', sa.String(length=36), nullable=True),
    sa.Column('parameters_json', sa.Text(), nullable=False),
    sa.Column('pricing_json', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['secret_ref_id'], ['secret_ref.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    with op.batch_alter_table('model_config_revision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_config_revision_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_config_revision_name'), ['name'], unique=False)

    op.create_table('evaluation_task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('benchmark_revision_id', sa.String(length=36), nullable=True),
    sa.Column('dataset_version_id', sa.String(length=36), nullable=True),
    sa.Column('model_config_revision_id', sa.String(length=36), nullable=True),
    sa.Column('agent_revision_id', sa.String(length=36), nullable=True),
    sa.Column('task_spec_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('budget_json', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'QUEUED', 'RUNNING', 'PAUSE_REQUESTED', 'PAUSED', 'SUCCEEDED', 'FAILED', 'BUDGET_EXHAUSTED', 'CANCELED')", name='evaluation_task_status'),
    sa.ForeignKeyConstraint(['agent_revision_id'], ['agent_revision.id'], ),
    sa.ForeignKeyConstraint(['benchmark_revision_id'], ['benchmark_revision.id'], ),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_version.id'], ),
    sa.ForeignKeyConstraint(['model_config_revision_id'], ['model_config_revision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_task_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_task_status'), ['status'], unique=False)
        batch_op.create_index('uq_evaluation_task_single_running', ['status'], unique=True, sqlite_where=sa.text("status = 'RUNNING'"))

    op.create_table('scenario',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_version_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenario_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenario_dataset_version_id'), ['dataset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenario_external_id'), ['external_id'], unique=False)

    op.create_table('case_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_version_id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_version.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_record_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_record_dataset_version_id'), ['dataset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_record_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_record_scenario_id'), ['scenario_id'], unique=False)

    op.create_table('run',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=9), nullable=False),
    sa.Column('run_spec_json', sa.Text(), nullable=False),
    sa.Column('run_spec_sha256', sa.String(length=64), nullable=False),
    sa.Column('next_case_index', sa.Integer(), nullable=False),
    sa.Column('pause_requested', sa.Boolean(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELED')", name='run_status'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['evaluation_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_task_id'), ['task_id'], unique=False)

    op.create_table('case_attempt',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=9), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('error_json', sa.Text(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=False),
    sa.Column('trajectory_summary_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELED')", name='case_attempt_status'),
    sa.ForeignKeyConstraint(['case_id'], ['case_record.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_attempt_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_attempt_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_attempt_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_attempt_status'), ['status'], unique=False)

    op.create_table('attribution',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_attempt_id', sa.String(length=36), nullable=False),
    sa.Column('taxonomy', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_attempt_id'], ['case_attempt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attribution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attribution_case_attempt_id'), ['case_attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attribution_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_attribution_label'), ['label'], unique=False)

    op.create_table('human_review',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attribution_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('reviewer_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attribution_id'], ['attribution.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['local_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('human_review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_human_review_attribution_id'), ['attribution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_human_review_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_human_review_created_at'))
        batch_op.drop_index(batch_op.f('ix_human_review_attribution_id'))

    op.drop_table('human_review')
    with op.batch_alter_table('attribution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attribution_label'))
        batch_op.drop_index(batch_op.f('ix_attribution_created_at'))
        batch_op.drop_index(batch_op.f('ix_attribution_case_attempt_id'))

    op.drop_table('attribution')
    with op.batch_alter_table('case_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_attempt_status'))
        batch_op.drop_index(batch_op.f('ix_case_attempt_run_id'))
        batch_op.drop_index(batch_op.f('ix_case_attempt_created_at'))
        batch_op.drop_index(batch_op.f('ix_case_attempt_case_id'))

    op.drop_table('case_attempt')
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_task_id'))
        batch_op.drop_index(batch_op.f('ix_run_status'))
        batch_op.drop_index(batch_op.f('ix_run_created_at'))

    op.drop_table('run')
    with op.batch_alter_table('case_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_record_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_case_record_external_id'))
        batch_op.drop_index(batch_op.f('ix_case_record_dataset_version_id'))
        batch_op.drop_index(batch_op.f('ix_case_record_created_at'))

    op.drop_table('case_record')
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenario_external_id'))
        batch_op.drop_index(batch_op.f('ix_scenario_dataset_version_id'))
        batch_op.drop_index(batch_op.f('ix_scenario_created_at'))

    op.drop_table('scenario')
    with op.batch_alter_table('evaluation_task', schema=None) as batch_op:
        batch_op.drop_index('uq_evaluation_task_single_running', sqlite_where=sa.text("status = 'RUNNING'"))
        batch_op.drop_index(batch_op.f('ix_evaluation_task_status'))
        batch_op.drop_index(batch_op.f('ix_evaluation_task_created_at'))

    op.drop_table('evaluation_task')
    with op.batch_alter_table('model_config_revision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_config_revision_name'))
        batch_op.drop_index(batch_op.f('ix_model_config_revision_created_at'))

    op.drop_table('model_config_revision')
    with op.batch_alter_table('dataset_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_version_name'))
        batch_op.drop_index(batch_op.f('ix_dataset_version_created_at'))
        batch_op.drop_index(batch_op.f('ix_dataset_version_benchmark_revision_id'))

    op.drop_table('dataset_version')
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_event_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_event_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_event_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_event_action'))

    op.drop_table('audit_event')
    with op.batch_alter_table('secret_ref', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_secret_ref_created_at'))

    op.drop_table('secret_ref')
    with op.batch_alter_table('local_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_local_user_username'))
        batch_op.drop_index(batch_op.f('ix_local_user_created_at'))

    op.drop_table('local_user')
    with op.batch_alter_table('benchmark_revision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_benchmark_revision_created_at'))
        batch_op.drop_index(batch_op.f('ix_benchmark_revision_adapter_name'))

    op.drop_table('benchmark_revision')
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_sha256'))
        batch_op.drop_index(batch_op.f('ix_artifact_ref_type'))
        batch_op.drop_index(batch_op.f('ix_artifact_ref_id'))
        batch_op.drop_index(batch_op.f('ix_artifact_kind'))
        batch_op.drop_index(batch_op.f('ix_artifact_created_at'))

    op.drop_table('artifact')
    with op.batch_alter_table('app_setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_setting_key'))
        batch_op.drop_index(batch_op.f('ix_app_setting_created_at'))

    op.drop_table('app_setting')
    with op.batch_alter_table('agent_revision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_revision_name'))
        batch_op.drop_index(batch_op.f('ix_agent_revision_created_at'))

    op.drop_table('agent_revision')
    # ### end Alembic commands ###
