import { FormEvent, useEffect, useState } from "react";
import { Activity, Plus, Radio } from "lucide-react";
import { apiFetch, ApiClientError, type AgentSummary } from "../api/client";
import { EmptyState, ErrorState, LoadingState, PageTitle } from "../components/PageStates";
import { HealthBadge } from "../components/HealthBadge";

export function AgentsPage() {
  const [agents, setAgents] = useState<AgentSummary[]>([]); const [kind, setKind] = useState<"BUILT_IN" | "SERVICE">("BUILT_IN"); const [showForm, setShowForm] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = async () => { setLoading(true); try { setAgents(await apiFetch<AgentSummary[]>("/api/v1/agents")); } catch (reason) { setError(reason instanceof ApiClientError ? reason.message : "Unable to load agents"); } finally { setLoading(false); } }; useEffect(() => { void load(); }, []);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setError(null); try { await apiFetch("/api/v1/agents", { method: "POST", json: { kind, revision_id: form.get("revision_id"), endpoint: kind === "SERVICE" ? form.get("endpoint") : undefined, manifest_sha256: kind === "SERVICE" ? form.get("manifest_sha256") : undefined } }); event.currentTarget.reset(); setShowForm(false); await load(); } catch (reason) { setError(reason instanceof ApiClientError ? reason.message : "Unable to register agent"); } }
  return <section className="page-frame"><PageTitle eyebrow="Runtime" title="Agents" detail="Allowlisted built-ins and manifest-pinned Agent Services." action={<button className="button button-primary" onClick={() => setShowForm((value) => !value)}><Plus size={15} />{showForm ? "Close" : "Register agent"}</button>} />
    {showForm && <form className="form-panel" onSubmit={create}><div className="form-grid"><label>Runtime type<select value={kind} onChange={(event) => setKind(event.target.value as "BUILT_IN" | "SERVICE")}><option value="BUILT_IN">Built-in</option><option value="SERVICE">Agent Service</option></select></label><label>Revision ID<input name="revision_id" required placeholder="secrl-baseline-v1" /></label>{kind === "SERVICE" && <><label className="span-2">Internal endpoint<input name="endpoint" required placeholder="http://agent-service:8080" /></label><label className="span-2">Manifest SHA-256<input name="manifest_sha256" pattern="[a-f0-9]{64}" required /></label></>}</div><button className="button button-primary">Save allowlisted revision</button></form>}
    {error && <ErrorState message={error} onRetry={() => void load()} />}{loading ? <LoadingState label="Loading agent revisions" /> : agents.length === 0 ? <EmptyState title="No agents registered" detail="Register a built-in revision or a manifest-pinned service." /> : <div className="resource-list">{agents.map((agent) => <article className="resource-row" key={agent.id}><div className="resource-main"><strong>{agent.name}</strong><span><Radio size={13} /> {agent.kind === "SERVICE" ? agent.endpoint : "Platform process"}</span><code>{agent.sha256.slice(0, 12)}…</code></div><div className="resource-meta"><HealthBadge status="healthy" /><span className="muted"><Activity size={13} /> Protocol v1</span></div></article>)}</div>}
  </section>;
}
