import { FormEvent, useState } from "react";
import { apiFetch, ApiClientError } from "../api/client";
import { ErrorState, PageTitle } from "../components/PageStates";

export function AnalysisReviewPage() {
  const [attributionId, setAttributionId] = useState(""); const [primary, setPrimary] = useState(""); const [confidence, setConfidence] = useState("medium"); const [notes, setNotes] = useState(""); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  async function submit(event: FormEvent) { event.preventDefault(); setMessage(null); setError(null); try { await apiFetch(`/api/v1/attributions/${attributionId}/reviews`, { method: "POST", json: { primary, secondary: [], confidence, evidence: [], notes } }); setMessage("Review revision appended to the audit history."); setPrimary(""); setNotes(""); } catch (reason) { setError(reason instanceof ApiClientError ? reason.message : "Unable to append review"); } }
  return <section className="page-frame"><PageTitle eyebrow="Failure analysis" title="Analysis & review" detail="Automatic attribution stays read-only; each human decision is an append-only revision." /><div className="review-layout"><section className="section-block"><h2>Analysis runs</h2><div className="empty-state large"><p>No analysis selected</p><span>Open Analysis from a completed Run to inspect evidence artifacts.</span></div></section><form className="form-panel" onSubmit={submit}><h2>Append HumanReview</h2><p className="muted">Review inputs are persisted with reviewer identity, prior revision and audit event.</p><label>Attribution ID<input value={attributionId} onChange={(event) => setAttributionId(event.target.value)} required /></label><label>Primary label<input value={primary} onChange={(event) => setPrimary(event.target.value)} required /></label><label>Confidence<select value={confidence} onChange={(event) => setConfidence(event.target.value)}><option>low</option><option>medium</option><option>high</option></select></label><label>Notes<textarea value={notes} onChange={(event) => setNotes(event.target.value)} rows={5} maxLength={4096} /></label>{message && <div className="form-success">{message}</div>}{error && <ErrorState message={error} />}<button className="button button-primary">Append review revision</button></form></div></section>;
}
