import { useEffect, useState } from "react";
import { Database, FileCheck2 } from "lucide-react";
import { apiFetch, ApiClientError, type BenchmarkSummary } from "../api/client";
import { EmptyState, ErrorState, LoadingState, PageTitle } from "../components/PageStates";

export function BenchmarksPage() {
  const [items, setItems] = useState<BenchmarkSummary[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const load = async () => { setLoading(true); try { setItems(await apiFetch<BenchmarkSummary[]>("/api/v1/benchmarks")); } catch (reason) { setError(reason instanceof ApiClientError ? reason.message : "Unable to load benchmarks"); } finally { setLoading(false); } }; useEffect(() => { void load(); }, []);
  return <section className="page-frame"><PageTitle eyebrow="Frozen inputs" title="Benchmarks" detail="Benchmark revisions, DatasetVersions, split and manifest integrity." />{error && <ErrorState message={error} onRetry={() => void load()} />}{loading ? <LoadingState label="Loading benchmark revisions" /> : items.length === 0 ? <EmptyState title="No benchmark revisions" detail="Platform adapters will appear after database initialization." /> : <div className="resource-list">{items.map((item) => { const manifest = item.manifest as Record<string, unknown>; const dataset = item.dataset as Record<string, unknown>; return <article className="resource-row" key={String(manifest.benchmark_id)}><div className="resource-main"><strong><Database size={15} /> {String(manifest.name ?? manifest.benchmark_id)}</strong><span>Revision {String(manifest.version ?? "—")} · protocol {String(manifest.protocol_version ?? "1")}</span><code>{String(dataset.sha256 ?? "").slice(0, 16)}…</code></div><div className="resource-meta"><span className="secure-state"><FileCheck2 size={14} />{String(dataset.case_count ?? "—")} cases</span><span className="muted">{String(dataset.version ?? "DatasetVersion")}</span></div></article>; })}</div>}</section>;
}
