import { FormEvent, useEffect, useState } from "react";
import { Check, KeyRound, Plus, RotateCcw } from "lucide-react";
import { apiFetch, ApiClientError, type ModelSummary } from "../api/client";
import { EmptyState, ErrorState, LoadingState, PageTitle } from "../components/PageStates";

export function ModelsPage() {
  const [models, setModels] = useState<ModelSummary[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [showForm, setShowForm] = useState(false); const [apiKey, setApiKey] = useState(""); const [pending, setPending] = useState(false);
  const load = async () => { setLoading(true); setError(null); try { setModels(await apiFetch<ModelSummary[]>("/api/v1/models")); } catch (reason) { setError(reason instanceof ApiClientError ? reason.message : "Unable to load models"); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(null); const formElement = event.currentTarget; const form = new FormData(formElement); try { await apiFetch("/api/v1/models", { method: "POST", headers: { "X-Model-API-Key": apiKey }, json: { name: form.get("name"), provider: "openai-compatible", endpoint: form.get("endpoint"), model: form.get("model"), parameters: { max_output_tokens: Number(form.get("max_output_tokens")) || undefined, timeout_seconds: Number(form.get("timeout_seconds")) || undefined }, pricing: { input_per_million: form.get("input_per_million") || undefined, output_per_million: form.get("output_per_million") || undefined } } }); formElement.reset(); setApiKey(""); setShowForm(false); await load(); } catch (reason) { setError(reason instanceof ApiClientError ? reason.message : "Unable to save model"); } finally { setPending(false); } }
  return <section className="page-frame"><PageTitle eyebrow="Configuration" title="Models" detail="Encrypted model credentials and immutable provider revisions." action={<button className="button button-primary" onClick={() => setShowForm((value) => !value)}><Plus size={15} />{showForm ? "Close" : "Add model"}</button>} />
    {showForm && <form className="form-panel" onSubmit={create}><div className="form-panel-heading"><div><h2>New model revision</h2><p className="muted">The key is sent once, encrypted server-side, then cleared from this form.</p></div><KeyRound size={18} /></div><div className="form-grid"><label>Name<input name="name" required placeholder="Local OpenAI" /></label><label>Model<input name="model" required placeholder="gpt-4o-mini" /></label><label className="span-2">Endpoint<input name="endpoint" required placeholder="https://api.example.test/v1" /></label><label>API key<input name="apiKey" type="password" value={apiKey} onChange={(event) => setApiKey(event.target.value)} autoComplete="new-password" required /></label><label>Max output tokens<input name="max_output_tokens" type="number" min="1" defaultValue="256" required /></label><label>Request timeout (s)<input name="timeout_seconds" type="number" min="1" max="600" placeholder="30–600, default 30" /></label><label>Input / 1M tokens<input name="input_per_million" type="number" min="0" step="0.000001" /></label><label>Output / 1M tokens<input name="output_per_million" type="number" min="0" step="0.000001" /></label></div><button className="button button-primary" disabled={pending}>{pending ? "Saving…" : "Save encrypted revision"}</button></form>}
    {error && <ErrorState message={error} onRetry={() => void load()} />}{loading ? <LoadingState label="Loading model revisions" /> : models.length === 0 ? <EmptyState title="No models configured" detail="Add a model revision to run a model-backed evaluation." /> : <div className="resource-list">{models.map((model) => <article className="resource-row" key={model.id}><div className="resource-main"><strong>{model.name}</strong><span>{model.provider} · {model.model}</span><code>{model.sha256.slice(0, 12)}…</code></div><div className="resource-meta"><span className={model.credential_configured ? "secure-state" : "warning-state"}>{model.credential_configured ? <><Check size={14} />Configured</> : <><RotateCcw size={14} />Missing key</>}</span><span className="muted">{model.pricing_configured ? "Pricing frozen" : "Pricing missing"}</span></div></article>)}</div>}
  </section>;
}
