import { FormEvent, useMemo, useState } from "react";
import { Check, ChevronLeft, ChevronRight, LockKeyhole, Play } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { apiFetch, ApiClientError } from "../api/client";
import { ErrorState, PageTitle } from "../components/PageStates";

const steps = ["Scope", "Runtime", "Reliability", "Budget / review"];

export function NewEvaluationPage() {
  const navigate = useNavigate(); const [step, setStep] = useState(0); const [benchmark, setBenchmark] = useState("protocol-smoke"); const [agent, setAgent] = useState("builtin-deterministic-smoke-v1"); const [model, setModel] = useState(""); const [cases, setCases] = useState("smoke-001"); const [maxSteps, setMaxSteps] = useState(32); const [maxStrLen, setMaxStrLen] = useState(100000); const [maxEntryReturn, setMaxEntryReturn] = useState(15); const [maxCases, setMaxCases] = useState(1); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false); const summary = useMemo(() => ({ benchmark, agent, model: model || "No model (deterministic)", cases: cases.split(",").map((item) => item.trim()).filter(Boolean), maxSteps, maxStrLen, maxEntryReturn, maxCases }), [agent, benchmark, cases, maxCases, maxEntryReturn, maxSteps, maxStrLen, model]);
  async function submit(event: FormEvent) { event.preventDefault(); if (step < steps.length - 1) { setStep((value) => value + 1); return; } setPending(true); setError(null); try { const result = await apiFetch<{ run_id: string }>("/api/v1/tasks", { method: "POST", json: { name: `${benchmark} evaluation`, benchmark_id: benchmark, agent_revision_id: agent, model_config_revision_id: model || null, case_ids: summary.cases, budget: { max_cases: maxCases }, max_steps: maxSteps, max_str_len: maxStrLen, max_entry_return: maxEntryReturn, agent_parameters: {} } }); navigate(`/runs/${result.run_id}`); } catch (reason) { setError(reason instanceof ApiClientError ? reason.message : "Unable to create evaluation"); } finally { setPending(false); } }
  return <section className="page-frame"><PageTitle eyebrow="Queue a run" title="New evaluation" detail="Create a frozen TaskSpec with explicit scope, runtime, limits and budget." /><div className="stepper" aria-label="Evaluation setup steps">{steps.map((label, index) => <div className={`step ${index <= step ? "step-active" : ""}`} key={label}><span>{index < step ? <Check size={13} /> : index + 1}</span>{label}</div>)}</div><form className="form-panel evaluation-form" onSubmit={submit}>{step === 0 && <div className="form-grid"><label>Benchmark revision<select value={benchmark} onChange={(event) => setBenchmark(event.target.value)}><option value="protocol-smoke">Protocol-Smoke v1</option><option value="secrl">SecRL fixture</option></select></label><label>Case IDs<input value={cases} onChange={(event) => setCases(event.target.value)} placeholder="smoke-001, smoke-002" /><span className="field-hint">Comma-separated IDs from the frozen DatasetVersion.</span></label></div>}{step === 1 && <div className="form-grid"><label>Agent revision<input value={agent} onChange={(event) => setAgent(event.target.value)} required /><span className="field-hint">Only registered, manifest-pinned revisions can run.</span></label><label>Model revision (optional)<input value={model} onChange={(event) => setModel(event.target.value)} placeholder="Required for model-backed agents" /></label></div>}{step === 2 && <div className="form-grid"><label>Max steps<input type="number" min="1" value={maxSteps} onChange={(event) => setMaxSteps(Number(event.target.value))} /></label><label>Max observation string length<input type="number" min="1" value={maxStrLen} onChange={(event) => setMaxStrLen(Number(event.target.value))} /></label><label>Max entry return<input type="number" min="1" value={maxEntryReturn} onChange={(event) => setMaxEntryReturn(Number(event.target.value))} /></label></div>}{step === 3 && <div><div className="review-summary"><LockKeyhole size={17} /><div><strong>Immutable run summary</strong><span>Limits are frozen into the RunSpec and cannot be changed by the agent.</span></div></div><dl className="summary-list">{Object.entries(summary).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{Array.isArray(value) ? value.join(", ") : String(value)}</dd></div>)}</dl></div>}{error && <ErrorState message={error} />}{<div className="form-actions">{step > 0 && <button type="button" className="button button-quiet" onClick={() => setStep((value) => value - 1)}><ChevronLeft size={15} />Back</button>}<button className="button button-primary" disabled={pending}>{step < steps.length - 1 ? <>Continue <ChevronRight size={15} /></> : <><Play size={15} />{pending ? "Queueing…" : "Queue evaluation"}</>}</button></div>}</form></section>;
}
