import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { apiFetch, ApiClientError } from "../api/client";
import { ErrorState, LoadingState, PageTitle } from "../components/PageStates";
import { HealthBadge } from "../components/HealthBadge";

type Run = { id: string; task_id: string; status: string; checkpoint: number; run_spec_sha256: string };

export function RunDetailPage() {
  const { id = "" } = useParams(); const [run, setRun] = useState<Run | null>(null); const [tab, setTab] = useState("Overview"); const [cases, setCases] = useState<unknown[] | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!id) return; void apiFetch<Run>(`/api/v1/runs/${id}`).then(setRun).catch((reason) => setError(reason instanceof ApiClientError ? reason.message : "Unable to load run")); }, [id]);
  async function selectTab(next: string) { setTab(next); if (next === "Cases" && cases === null) { try { setCases(await apiFetch<unknown[]>(`/api/v1/runs/${id}/cases`)); } catch (reason) { setError(reason instanceof ApiClientError ? reason.message : "Unable to load cases"); } } }
  async function transition(action: "pause" | "resume" | "cancel") { try { const next = await apiFetch<{ status: string }>(`/api/v1/runs/${id}:${action}`, { method: "POST" }); setRun((value) => value ? { ...value, status: next.status } : value); } catch (reason) { setError(reason instanceof ApiClientError ? reason.message : "Run state transition failed"); } }
  if (error && !run) return <section className="page-frame"><ErrorState message={error} /></section>; if (!run) return <section className="page-frame"><LoadingState label="Loading run" /></section>;
  return <section className="page-frame"><PageTitle eyebrow="Run detail" title={run.id.slice(0, 12)} detail={`Checkpoint ${run.checkpoint} · RunSpec ${run.run_spec_sha256.slice(0, 16)}…`} action={<HealthBadge status={run.status} />} /><div className="toolbar"><button className="button button-quiet" onClick={() => void transition("pause")} disabled={!['QUEUED', 'RUNNING'].includes(run.status)}>Pause</button><button className="button button-quiet" onClick={() => void transition("resume")} disabled={!['PAUSED'].includes(run.status)}>Resume</button><button className="button button-danger" onClick={() => void transition("cancel")} disabled={['SUCCEEDED', 'FAILED', 'CANCELED'].includes(run.status)}>Cancel</button></div><div className="tabs" role="tablist">{["Overview", "Cases", "Trajectory", "Analysis", "Artifacts", "Audit"].map((name) => <button key={name} role="tab" aria-selected={tab === name} className={tab === name ? "tab-active" : ""} onClick={() => void selectTab(name)}>{name}</button>)}</div><div className="tab-panel">{tab === "Overview" && <dl className="summary-list"><div><dt>Status</dt><dd>{run.status}</dd></div><div><dt>Task</dt><dd>{run.task_id}</dd></div></dl>}{tab === "Cases" && (cases === null ? <LoadingState label="Loading cases" /> : cases.length === 0 ? <div className="muted">No case attempts recorded.</div> : <pre className="code-block">{JSON.stringify(cases, null, 2)}</pre>)}{tab !== "Overview" && tab !== "Cases" && <div className="empty-state large"><p>{tab} is available once the run produces the corresponding artifact.</p><span>Full trajectories are loaded only on explicit request.</span></div>}</div>{error && <ErrorState message={error} />}</section>;
}
